"""Extract REAL first-layer 1D-CNN activations on one real PHM window.

Generates ``web/src/lib/cnnFeatmap.ts`` — a small fixed teaching asset for the
CnnFeatureSlider animation in the training simulator. The activations are REAL
(a trained CNN run on a real HI-degradation window), so the animation shows how
the network actually extracts features, not an illustration.

Run: python -m src.models.servo_cnn_featmap
"""
from __future__ import annotations

import json

import numpy as np
import torch
import torch.nn as nn

from src.models.servo_cnn import _CNN, _set_seed
from src.utils.paths import load_config, resolve

# plain-language Chinese descriptions per raw channel (for the UI legend)
CHANNEL_ZH = {
    "torque_std": "扭矩波動",
    "rotor_speed_std": "轉速波動",
    "i_3p_a_std": "三相電流 A",
    "i_3p_b_std": "三相電流 B",
    "i_3p_c_std": "三相電流 C",
    "direct_std": "D 軸電流",
    "quadrature_std": "Q 軸電流（扭矩相關）",
    "position_error_std": "位置誤差",
}


def main() -> None:
    cfg = load_config()["servo"]
    d = np.load(resolve(cfg["windows_path"]), allow_pickle=True)
    X, y, split = d["X"].astype(np.float32), d["y"].astype(np.int64), d["split"]
    labels = [str(c) for c in d["labels"]]
    channels = [str(c) for c in d["channels"]]
    tr, te = split == "train", split != "train"
    mu = X[tr].mean(axis=(0, 2), keepdims=True)
    sd = X[tr].std(axis=(0, 2), keepdims=True) + 1e-6
    Xs = (X - mu) / sd

    _set_seed(42)
    model = _CNN(len(channels), len(labels))
    opt = torch.optim.Adam(model.parameters(), lr=1e-3)
    ce = nn.CrossEntropyLoss()
    rng = np.random.default_rng(42)
    Xtr, ytr = torch.from_numpy(Xs[tr]), torch.from_numpy(y[tr])
    model.train()
    for _ in range(50):
        perm = rng.permutation(len(Xtr))
        for s in range(0, len(Xtr), 16):
            idx = perm[s:s + 16]
            opt.zero_grad()
            ce(model(Xtr[idx]), ytr[idx]).backward()
            opt.step()
    model.eval()

    hi = labels.index("HI")
    te_idx = np.where(te)[0]
    with torch.no_grad():
        pred = model(torch.from_numpy(Xs[te])).argmax(1).numpy()
    sel = te_idx[[i for i, gi in enumerate(te_idx) if y[gi] == hi and pred[i] == hi][0]]
    x1 = Xs[sel]
    with torch.no_grad():
        act = model.features[:3](torch.from_numpy(x1[None])).numpy()[0]  # (16,128) real conv1

    ch_order = np.argsort(x1.std(1))[::-1][:3]
    f_order = np.argsort(act.std(1))[::-1][:6]
    r2 = lambda a: [[round(float(v), 2) for v in row] for row in a]
    obj = {
        "label": labels[hi],
        "in_channels": [channels[c] for c in ch_order],
        "in_channels_zh": [CHANNEL_ZH.get(channels[c], channels[c]) for c in ch_order],
        "input": r2(x1[ch_order]),
        "filters": r2(act[f_order]),
        "kernel": 7,
        "stride": 2,
        "n_in": int(x1.shape[1]),
        "n_feat": int(act.shape[1]),
    }

    ts = (
        "// Auto-generated by `python -m src.models.servo_cnn_featmap` — do not edit by hand.\n"
        "// REAL first-layer 1D-CNN activations on one real PHM window (health state HI),\n"
        "// used by the CnnFeatureSlider teaching animation in the training simulator.\n"
        "export interface CnnFeatmap {\n"
        "  label: string;\n"
        "  in_channels: string[];\n"
        "  in_channels_zh: string[];\n"
        "  input: number[][];\n"
        "  filters: number[][];\n"
        "  kernel: number;\n"
        "  stride: number;\n"
        "  n_in: number;\n"
        "  n_feat: number;\n"
        "}\n"
        "export const CNN_FEATMAP: CnnFeatmap = " + json.dumps(obj, ensure_ascii=False) + ";\n"
    )
    out = resolve("web/src/lib/cnnFeatmap.ts")
    out.write_text(ts, encoding="utf-8")
    print(f"[featmap] label={obj['label']} channels={obj['in_channels_zh']} -> {out}")


if __name__ == "__main__":
    main()
